CXX=g++
CXXFLAGS=-g -Wall -std=c++17 -DCPP_STANDALONE -I./ -Igomea/ -IEigen/

SRCDIR=gomea/src
OBJDIR=build/obj
BINDIR=build

# list of all source files
SRCS=$(wildcard $(SRCDIR)/mixed_integer/*.cpp $(SRCDIR)/fitness/*.cpp $(SRCDIR)/fitness/benchmarks-discrete/*.cpp $(SRCDIR)/common/*.cpp $(SRCDIR)/utils/*.cpp)

# generate a list of object files based on source files
OBJS=$(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%.o,$(SRCS))

# the final executable file
TARGET=$(BINDIR)/MixedIntegerGOMEA

default: cpp_MI

# compile object files
$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# link object files to generate executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $^ -o $@

here: 
	python3 setup.py build_ext --inplace

cpp:
	@mkdir -p build
	g++ -g -Wall -std=c++17 -DCPP_STANDALONE -I./ -Igomea/ -IEigen/ gomea/src/discrete/*.cpp gomea/src/fitness/*.cpp gomea/src/common/*.cpp gomea/src/utils/*.cpp -o build/DiscreteGOMEA

# cpp_MI target depends on the executable file
cpp_MI: $(TARGET)

debug:
	python3 setup.py build_ext --inplace --debug

install:
	pip -q install build --user
	pip -q install cython --user
	python3 -m build --wheel
	pip install dist/*.whl --user

reinstall:
	python3 setup.py bdist_wheel
	pip install dist/*.whl --user --force-reinstall

doc:
	sphinx-build -b html docs/source/ docs/build/html

clean:
	rm -f *.so
	rm -rf gomea.egg-info/
	rm -rf build/
	rm -rf dist/
	rm -f gomea/*.cpp
	rm -f gomea/*.h
	rm -f gomea/*.so
	rm -rf cython_debug/
	rm -rf gomea/__pycache__/

# include dependencies generated by the compiler
-include $(OBJS:.o=.d)
